name: Build & Deploy Angular (SSH)

on:
  push:
    branches: [ "main" ]

concurrency:
  group: deploy-main
  cancel-in-progress: true

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: "npm"

      - name: Install dependencies
        working-directory: ./personal-site
        run: npm ci

      - name: Build
        working-directory: ./personal-site
        run: |
          ng build
          --base-href /Personal-Site/ \
          --configuration production

      - name: Deploy
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          DEPLOY_TARGET: ${{ secrets.DEPLOY_TARGET }}
        working-directory: ./personal-site
        run: |
          # Write key to temporary file.
          echo "$SSH_PRIVATE_KEY" > key.pem
          chmod 600 key.pem

          # Copy files
          scp -r \
            -i key.pem \
            -o StrictHostKeyChecking=no \
            dist/personal-site/* \
            "$DEPLOY_TARGET"

          # Clean up
          rm key.pem
